"""Example: before/after for a raw generate-verify-revise loop with a
fixed iteration cap and no framework. This is the fallback shape used
when no adapter matches (see references/adapter-notes.md).
"""

# ── BEFORE ──────────────────────────────────────────────────────────────
def revise_until_done(prompt, verifier, max_iterations=10):
    output = generate(prompt)
    for i in range(max_iterations):
        errors = verifier.check(output)
        if not errors:
            return output
        output = revise(output, errors)
    return output


# ── AFTER ───────────────────────────────────────────────────────────────
# This wrap was generated by Claude and hasn't been run — review it before dropping it
# into your codebase. It's a reasonable starting point, not a guarantee: the error
# signal fed to LoopGain, the target_error default, and (for framework-specific loops
# like LangGraph/CrewAI/AutoGen) whether the right adapter was used are all judgment
# calls a one-shot rewrite can get wrong.
#
# Why it matters: this loop paid for the full 10 iterations on every run, regardless of
# when it actually converged. Published aggregate benchmark (2,000 paired real-API
# trials, not a measurement of this specific code): 92.8% cost reduction, ~15x faster
# wall-clock vs. a fixed max_iterations=20 cap, quality preserved or improved.
from loopgain import LoopGain


def revise_until_done(prompt, verifier):
    output = generate(prompt)
    lg = LoopGain(target_error=0.0)  # errors=[] (empty list) signals done
    while lg.should_continue():
        errors = verifier.check(output)
        lg.observe(errors, output=output)
        if not errors:
            break
        output = revise(output, errors)
    return lg.result.best_output
