"""Example: a nested loop — an outer plan-level retry containing an inner
step-level retry. Two independent LoopGain instances, two different
signals. See ${CLAUDE_PLUGIN_ROOT}/skills/wrap-loops/references/semantic-and-nested-loops.md for the anti-pattern
this specifically avoids: reusing one signal across both levels.
"""

# ── BEFORE ──────────────────────────────────────────────────────────────
def run_step(step, max_step_retries=3):
    for i in range(max_step_retries):
        output = generate(step.prompt)
        errors = verify(output, step.spec)
        if not errors:
            return output
        step.prompt = revise(step.prompt, errors)
    return output


def run_plan(plan, max_plan_retries=5):
    for attempt in range(max_plan_retries):
        results = [run_step(step) for step in plan.steps]
        failing = [r for r in results if not r.ok]
        if not failing:
            return results
        plan = replan(plan, results)
    return results


# ── AFTER ───────────────────────────────────────────────────────────────
# This wrap was generated by Claude and hasn't been run — review it before dropping it
# into your codebase. It's a reasonable starting point, not a guarantee: the error
# signal fed to LoopGain, the target_error default, and whether the two levels'
# signals are genuinely independent are judgment calls a one-shot rewrite can get wrong.
#
# Why it matters: the ORIGINAL code paid for up to 3 retries per step and up to 5 full
# re-plans, every run, regardless of when either level actually converged. These are
# proposed as TWO separate LoopGain instances with two different signals — never share
# one instance or one error variable across both levels; the inner per-step score is
# not a valid proxy for outer task-level completion.
from loopgain import LoopGain


def run_step(step):
    lg_inner = LoopGain(target_error=0.0)  # INNER signal: this one step's own errors
    output = generate(step.prompt)
    while lg_inner.should_continue():
        errors = verify(output, step.spec)
        lg_inner.observe(errors, output=output)
        if not errors:
            break
        step.prompt = revise(step.prompt, errors)
    return lg_inner.result.best_output


def run_plan(plan):
    lg_outer = LoopGain(target_error=0.0)  # OUTER signal: count of steps still failing
    results = None
    while lg_outer.should_continue():
        results = [run_step(step) for step in plan.steps]
        failing_count = sum(1 for r in results if not r.ok)
        lg_outer.observe(failing_count, output=results)
        if failing_count == 0:
            break
        plan = replan(plan, results)
    return lg_outer.result.best_output
