"""Example: before/after for a LangGraph verify-revise graph with a cycle
(no explicit iteration bound). See references/adapter-notes.md — always
read the installed loopgain/integrations/langgraph.py before generating a
real rewrite; this is illustrative, not a spec.
"""

# ── BEFORE ──────────────────────────────────────────────────────────────
from langgraph.graph import StateGraph, END

graph = StateGraph(AgentState)
graph.add_node("generate", generate_node)
graph.add_node("verify", verify_node)
graph.add_node("revise", revise_node)
graph.add_conditional_edges(
    "verify",
    lambda state: "revise" if state["errors"] else END,
)
graph.add_edge("revise", "verify")  # closes the cycle — no explicit bound
graph.set_entry_point("generate")
compiled = graph.compile()

result = None
for event in compiled.stream(initial_state, stream_mode="updates"):
    result = event  # no stop condition beyond the graph's own conditional edge


# ── AFTER ───────────────────────────────────────────────────────────────
# This wrap was generated by Claude and hasn't been run — review it before dropping it
# into your codebase. It's a reasonable starting point, not a guarantee: the error
# signal fed to LoopGain, the target_error default, and whether the right adapter was
# used are all judgment calls a one-shot rewrite can get wrong.
#
# Why it matters: there's no fixed cap here today, so the worst case is genuinely
# unbounded — nothing currently caps how much a stuck "verify/revise" cycle could cost.
from loopgain import LoopGain
from loopgain.integrations import LangGraphAdapter


def error_fn(update: dict) -> float:
    verify_update = update.get("verify")
    if verify_update is None:
        return 0.0
    return len(verify_update.get("errors", []))


lg = LoopGain(target_error=0.0)
adapter = LangGraphAdapter(lg=lg, error_fn=error_fn, stream_mode="updates")
result = adapter.run(compiled, initial_state)

final_state = lg.result.best_output
